/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/MpZ9VNH6GM7
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { JSX, SVGProps } from "react"

export function Component() {
  return (
    <>
      <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 bg-[#3b2314] text-gray-100">
        <div className="container px-4 md:px-6">
          <div className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none text-gray-100">
                  Discover Your Next Musical Obsession
                </h1>
                <p className="max-w-[600px] text-gray-400 md:text-xl">
                  Explore our curated collection of the latest albums, instruments, and accessories to elevate your
                  musical journey.
                </p>
              </div>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-[#a07d5e] px-8 text-sm font-medium text-gray-900 shadow transition-colors hover:bg-[#b28f70] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-300 disabled:pointer-events-none disabled:opacity-50 dark:bg-[#3b2314] dark:text-gray-100 dark:hover:bg-[#2d1c10]"
                href="#"
              >
                Shop Now
              </Link>
            </div>
            <img
              alt="Hero"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-bottom sm:w-full lg:order-last lg:aspect-square"
              height="550"
              src="/placeholder.svg"
              width="550"
            />
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-[#3b2314] text-gray-100">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Top Selling Products</h2>
            <p className="mx-auto max-w-[700px] text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Discover the latest must-have music gear and accessories.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 mt-8">
            <Card className="bg-[#2d1c10] text-gray-100">
              <CardHeader>
                <img
                  alt="Product"
                  className="aspect-square object-cover rounded-t-lg"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <h3 className="text-lg font-semibold">Fender American Professional II Stratocaster</h3>
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-gray-600 stroke-gray-600" />
                    <StarIcon className="w-4 h-4 fill-gray-600 stroke-gray-600" />
                    <span>(42)</span>
                  </div>
                  <div className="font-bold text-2xl">$1,499.99</div>
                </div>
              </CardContent>
              <CardFooter>
                <Button
                  className="w-full bg-[#a07d5e] text-[#3b2314] hover:bg-[#b28f70] dark:bg-[#3b2314] dark:text-gray-100 dark:hover:bg-[#2d1c10]"
                  size="sm"
                >
                  Add to Cart
                </Button>
              </CardFooter>
            </Card>
            <Card className="bg-[#2d1c10] text-gray-100">
              <CardHeader>
                <img
                  alt="Product"
                  className="aspect-square object-cover rounded-t-lg"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <h3 className="text-lg font-semibold">Yamaha P-125 88-Key Weighted Action Digital Piano</h3>
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-gray-600 stroke-gray-600" />
                    <span>(58)</span>
                  </div>
                  <div className="font-bold text-2xl">$599.99</div>
                </div>
              </CardContent>
              <CardFooter>
                <Button
                  className="w-full bg-[#a07d5e] text-[#3b2314] hover:bg-[#b28f70] dark:bg-[#3b2314] dark:text-gray-100 dark:hover:bg-[#2d1c10]"
                  size="sm"
                >
                  Add to Cart
                </Button>
              </CardFooter>
            </Card>
            <Card className="bg-[#2d1c10] text-gray-100">
              <CardHeader>
                <img
                  alt="Product"
                  className="aspect-square object-cover rounded-t-lg"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <h3 className="text-lg font-semibold">Shure SM58 Cardioid Dynamic Vocal Microphone</h3>
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <span>(72)</span>
                  </div>
                  <div className="font-bold text-2xl">$99.99</div>
                </div>
              </CardContent>
              <CardFooter>
                <Button
                  className="w-full bg-[#a07d5e] text-[#3b2314] hover:bg-[#b28f70] dark:bg-[#3b2314] dark:text-gray-100 dark:hover:bg-[#2d1c10]"
                  size="sm"
                >
                  Add to Cart
                </Button>
              </CardFooter>
            </Card>
            <Card className="bg-[#2d1c10] text-gray-100">
              <CardHeader>
                <img
                  alt="Product"
                  className="aspect-square object-cover rounded-t-lg"
                  height="300"
                  src="/placeholder.svg"
                  width="300"
                />
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  <h3 className="text-lg font-semibold">Focusrite Scarlett 2i2 USB Audio Interface</h3>
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-gray-600 stroke-gray-600" />
                    <span>(64)</span>
                  </div>
                  <div className="font-bold text-2xl">$159.99</div>
                </div>
              </CardContent>
              <CardFooter>
                <Button
                  className="w-full bg-[#a07d5e] text-[#3b2314] hover:bg-[#b28f70] dark:bg-[#3b2314] dark:text-gray-100 dark:hover:bg-[#2d1c10]"
                  size="sm"
                >
                  Add to Cart
                </Button>
              </CardFooter>
            </Card>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-[#2d1c10] text-gray-100">
        <div className="container px-4 md:px-6">
          <div className="space-y-4 text-center">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">What Our Customers Say</h2>
            <p className="mx-auto max-w-[700px] text-gray-400 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              Hear from our satisfied customers about their experiences with our products and services.
            </p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 mt-8">
            <Card className="bg-[#2d1c10] text-gray-100">
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                  </div>
                  <p className="text-sm leading-relaxed text-gray-400">
                    "I've been using the Fender American Professional II Stratocaster for a few months now, and it's
                    been an absolute game-changer. The tone and playability are incredible, and it's quickly become my
                    go-to guitar for both practice and live performances."
                  </p>
                  <div className="flex items-center gap-2">
                    <Avatar>
                      <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div className="grid gap-0.5 text-xs">
                      <div className="font-medium">John Doe</div>
                      <div className="text-gray-400">Musician</div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card className="bg-[#2d1c10] text-gray-100">
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-gray-600 stroke-gray-600" />
                  </div>
                  <p className="text-sm leading-relaxed text-gray-400">
                    "The Yamaha P-125 digital piano has been a game-changer for my home studio. The weighted keys and
                    realistic piano sound have helped me improve my playing, and the compact size makes it easy to fit
                    in my small space."
                  </p>
                  <div className="flex items-center gap-2">
                    <Avatar>
                      <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
                      <AvatarFallback>SA</AvatarFallback>
                    </Avatar>
                    <div className="grid gap-0.5 text-xs">
                      <div className="font-medium">Sarah Anderson</div>
                      <div className="text-gray-400">Pianist</div>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
            <Card className="bg-[#2d1c10] text-gray-100">
              <CardContent>
                <div className="space-y-4">
                  <div className="flex items-center gap-2 text-sm text-gray-400">
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                    <StarIcon className="w-4 h-4 fill-[#a07d5e]" />
                  </div>
                  <p className="text-sm leading-relaxed text-gray-400">
                    "The Shure SM58 microphone has been an essential part of my live setup for years. The sound quality
                    is incredible, and it's incredibly durable, even after being dropped a few times on stage. Highly
                    recommend it to any musician or vocalist."
                  </p>
                  <div className="flex items-center gap-2">
                    <Avatar>
                      <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
                      <AvatarFallback />
                    </Avatar>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>
    </>
  )
}

function StarIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
